### PR TITLE
Master

### PR DESCRIPTION
**Pull request by cgalvan**

### CODE REVIEW

**Comment by MeoMix** [comment]
? Mistake?

**Comment by cgalvan** [comment]
Yeah this was a mistake :)

**Comment by cgalvan** [comment]
I have a fix for #510 I was trying to submit a pull request for, this is my
first time doing one though so I messed it up, I apologize for that!

**Comment by MeoMix** [comment]
It's all good :) Yeah the tooltip thing has to do with me delaying rendering of tooltips until mouseover for performance but then it doesn't detect the initial mouseover event. :(

**Comment by cgalvan** [comment]
Yeah I'm still getting my feet wet with the code base so I wanted to start
with something small.  I have a fix that seems to work by triggering the
mouseenter event at the end of _setTooltips, I'm not sure if this is the
best way but wanted to get your opinion on it.

**Comment by MeoMix** [comment]
I think that's the approach I would take with a comment explaining it. The other way is to do the application of behaviors earlier, but I'm kinda opposed to that as it starts to slow down initial page load.

**Pull request closed without merging**
