### PR TITLE
Allows space bar to toggle player state

### LINKED ISSUE #396: When Streamus' UI has focus (and not an input), pressing spacebar should toggle play/pause
It's a very common feature from all media players of old and I've had several requests for this functionality to be supported.

### PR DESCRIPTION
**Pull request by jcme**
Still very much just playing around and getting the feel of the codebase, so if you want anything to be re-factored or if I've missed any edge cases please do let me know :)

This PR simply enables the spacebar to toggle playback when the foreground UI is open, but no input elements (e.g. search bar) have focus.

I was somewhat hesitant about binding window events in playPauseButtonView (it seems a bit sneaky to hide global event handlers this far in - I would've preferred to sit alongside the other window events in foregroundAreaView), but it was cleanest in terms of already having access to the required playPauseButton model.

Resolves #396

### CODE REVIEW

**Comment by MeoMix** [comment]
Hummmmm. Okay, cool. I do see where you're going with this.

I agree with your concern regarding pushing an event listener that far down into a view. At the very least you should be calling removeEventListener in the view's onBeforeDestroy method just in case its lifetime ends up being shorter than the window, but it's not currently.

However, I think the correct answer is to bind an event listener where the rest of them are bound -- in foregroundAreaView, and then leverage an application channel. Something like:

Streamus.channels.playPauseButton.commands.trigger('tryToggle:playerState');

Also, it's worth noting that it is never appropriate to explicitly call an event handler. A future change to code could anticipate _onClick being given click event arguments and you've broken that. I would move the logic for _onClick into its own method and call that. i.e.:

    _tryTogglePlayerState: function(){
        this.model.tryTogglePlayerState();
    }

That way we can also hook this method up to our commands event handler while maintaining proper naming conventions:

    this.listenTo(Streamus.channels.playPauseButton.commands, 'tryToggle:playerState', this._tryTogglePlayerState);

I do like the fact that you've introduced a KeyCode enum. I always liked using the one from jQuery UI, but I am trying to not leverage that -- so introducing one does make sense.

I also think it's good that you bound to the keydown event. Testing other shortcuts it does look like they fire on keydown and not on keypress or keyup.

What do you think?

**Comment by jcme** [comment]
Thanks for your feedback! Especially the point around not calling a click handler directly, I'd entirely missed why that was a bad idea.

I agree with all the suggestions you've made, hopefully the recent commit implements them. The solution feels a lot cleaner.

Thanks again for the detailed review

**Comment by MeoMix** [comment]
Looks good! The only thing I'd have a slight question on is whether it's appropriate to check the key first or whether the document is active.

Generally speaking -- reading the state of the DOM is expensive. If this scenario was "If body has class 'active' and I pressed spacebar then do thing" then it would be 100% for sure that you should check for spacebar first because reading that class forces a render.

In this scenario, I suspect that the value we get is cached... but I'm going to swap the checks around just for the sake of it.

**Comment by MeoMix** [comment]
Oh, also, be sure to always use === rather than ==. :)

**Comment by jcme** [comment]
Okay, thanks! Makes sense :)

**Pull request merged**
