### PR TITLE
added media key functionality

### PR DESCRIPTION
**Pull request by jeffzemla**
Added media key functionality (issue #118) by taking code from https://github.com/borismus/keysocket

### CODE REVIEW

**Comment by MeoMix** [comment]
Err....

This code doesn't do anything. You're on the master branch, not the development branch. The development branch already sets MediaKey defaults for the keyboard shortcuts: https://github.com/MeoMix/StreamusChromeExtension/blob/Development/src/manifest.json#L30

and listens for those shortcuts: https://github.com/MeoMix/StreamusChromeExtension/blob/Development/src/js/background/model/buttons/nextButton.js#L39

I think what I was attempting to convey in that issue was that certain media keys don't correctly work (such as mac media keys), but I don't think there's anything that can be done with that from Streamus' side.

Sorry, I'll go ahead and close that issue as I can see why it'd be confusing. Do try and work on the Development branch though as it's what is up to date for devs.

**Comment by jeffzemla** [comment]
Sorry for not using dev branch, I'm new to github.

But... I just downloaded the dev branch and the media keys do not work. I can see that they're set as the default keyboard shortcuts, but they don't do anything. The media keys work fine on my Mac in the commit I submitted.

**Comment by MeoMix** [comment]
Okay, interesting, I have two questions then:

1) Are you trying to test them globally? I don't set any keyboard shortcut global by default because people get confused really easily. If they want global then they can configure it.

2) I see a reference to js/mediakey.js in the PR, but I don't see mediakey.js actually included in the PR. Is that doing something to make the keys work on your mac?

**Comment by jeffzemla** [comment]
Ah, I see. The media keys do work in the dev version, but only when set to Global. Sorry!

**Comment by MeoMix** [comment]
No worries! <3 I really appreciate you taking a look at the code and talking to me about it! Sorry the PR didn't work out.

**Pull request closed without merging**
