### PR TITLE
Add right-click context menu options to the "Now Playing" area

### LINKED ISSUE #457: Add context menu options to the 'Now Playing' area

### PR DESCRIPTION
**Pull request by jcme**
Another (hopefully) straight forward one for you. Mostly an identical implementation of the context menu from other views that supports it.

Fixes #457 :)

### CODE REVIEW

**Comment by MeoMix** [comment]
Hey, so this looks reasonably good.

I think something worth asking is "Do we ever expect the context items presented in the 'now playing' area to be different than those on a 'stream item'"

If the answer is "Yes" then the code is good as-is. If the answer is "No" then we should move this code into an "action" module (see: https://github.com/MeoMix/StreamusChromeExtension/blob/Development/src/js/foreground/model/playlistAction.js) in order to keep the logic DRY across multiple views.

Personally, I struggle to think of a reason why this code should not be DRY.

**Comment by jcme** [comment]
I agree - can't think of any reason that the context menu options would need to differ between the ActiveStreamItem and any other StreamItem.

Hopefully that most recent commit is broadly in line with what you were expecting. ContextMenuAction has been implemented as per your suggestion.

I also noticed that currently playlistItemView and searchResultView are duplicating those same context menu options too, though I'm not sure if you had plans for them to diverge in the future. I've wired them up to the new action for now.

**Comment by MeoMix** [comment]
:clap: :clap: :clap:  THANK YOU!

Looks great. Really appreciate all your work.

**Comment by MeoMix** [comment]
@jcme So... already thought of something.

A user wants to save the 'now playing' song into a playlist. Their Stream has 200 songs in it and they can't find it. The context menu doesn't have a 'save' option because it's presented when hovering over the menu item, but there's no icons when interacting with the 'now playing' title area. So, maybe that option should be available in the context menu?

**Comment by jcme** [comment]
Interesting one, @MeoMix 

That's a good point - it feels like a legitimate use of the now playing context menu. Perhaps ContextMenuAction should take a list of 'actions' that each instance wishes to expose? e.g. `['save', 'copyUrl']` so that we still get some code reuse? Thoughts?

P.S. Hoping to pick up a couple of new cards soon - ended up being a busy weekend!

**Pull request merged**
