### PR TITLE
Browser settings merged into Settings

### PR DESCRIPTION
**Pull request by L3K0V**
Closes MeoMix/StreamusChromeExtension#316

### CODE REVIEW

**Comment by MeoMix** [comment]
:clap: I'll have a look. Thank you!

**Comment by L3K0V** [comment]
Maybe would be nice if settings dialog is a bit larger, what do you think? I tryed with fixed 400px and looks nice.

**Comment by MeoMix** [comment]
Yeah I'll play around with that. The only other thing I can think of, but it isn't a huge deal, is that any values for BrowserSettings currently written to localStorage are lost with this change. It's not too hard to load them up though, so I'll do that. :) TY!

**Comment by L3K0V** [comment]
Ouch... I will catch up. I had similar idea like Streamus, but when I saw your extension a told my self that will help you! For me there are new technologies used here and as you see I get in with little changes and things :) I've implemented showing view count of videos, may I open an Issue? Do you think is nice cosmetic?

**Comment by MeoMix** [comment]
Feel free to submit it and I can take a look, but I'm trying to keep
everything 'generic' so that when I add support for SoundCloud you
won't see some data only for some songs. I think SoundCloud does have
view count, though, so it might be fine. I'm just not sure what value
view count adds to the user's experience?

**Comment by L3K0V** [comment]
When make generic search, new artist for example simple view count will indicate you which song to play. Most people prefer quality, better quality -> more view count I think. Correct me if I'm wrong.
And another question while you are here - Is there plan for supporting youtube profile sync, for example - I cannot add my Watch Later playlist or if I like some Radio song, there isn't fast way to like it and add it to my favorites. In maner of this question I didn't check YouTube API capabilities but think that must be possible

**Comment by MeoMix** [comment]
I dunno, I feel like YouTube's algorithm for suggesting songs is pretty good at suggesting the best one as the first result, but it's worth thinking about. It's just that.. well, there's over 100 currently active issues and none of those have been from users requests the view count to be shown on search results. So, if it is useful, it's certainly not impacting day to day use enough for someone to bring it up.

You can import playlists into Streamus... does that not work for watch later? I don't really want to become more coupled with YouTube if at all possible. The long term goal with Streamus is to support other APIs such as SoundCloud and become a generic music player rather than one specifically built for YouTube.

**Pull request merged**
